#!/bin/sh
path=/home/simmondsdj/scripts/test; export path PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/sbin:/usr/sbin:/usr/local/packages/torque/2.4.16/bin:/usr/kerberos/bin:${path} d=x; e=y
cd $path; qsubTest test_cron_qsubTest_echo echoTest
